CREATE TABLE IF NOT EXISTS shopeeuser (
  user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(10) NOT NULL DEFAULT '',
    password VARCHAR(20) NOT NULL DEFAULT '',
    email VARCHAR(25) NOT NULL DEFAULT '',
    role VARCHAR(25) NOT NULL DEFAULT '',
    insertdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_unique UNIQUE (username, email)
    );

